// Reconstructed from MikeCore — 46 properties

struct GNView {
    float                    _scaleArrayFilterFactor;
    int32_t                  _centDisplayReferencePitchIndex;
    bool                     _centDisplayModePlusMinus;
    int32_t                  _pitchDisplayMode;
    int32_t                  _selectedPitchIndex;
    int32_t                  _clickedPitchIndex;
    float                    _clickedPitch;
    bool                     _pitchIndexIsHit;
    int32_t                  _closestPitchIndex;
    float                    _closestPitch;
    bool                     _detectionIsCyclic;
    int32_t                  _detectionCycleSizeCent;
    int32_t                  _detectionMinPitchCent;
    int32_t                  _detectionMaxPitchCent;
    bool                     _applyDetectionToScale;
    bool                     _detectionInsertsChromaticIntervals;
    bool                     _scaleWasJustDetected;
    float                    _preferredFundamentalPitchForDetection;
    bool                     _movingTuningPitchAnchor;
    bool                     _setTuningPitchAnchor;
    float                    _tuningPitchAnchorAnimationOffset;
    float                    _hertzScaleInAnimationLevel;
    float                    _hertzScaleOutAnimationLevel;
    GNTimeInterval*          _movingScaleIndicatorDisplayDelay;
    bool                     _movingScaleTuning;
    bool                     _movingScaleMode;
    bool                     _movingDetectedScale;
    float                    _movingTuningOffset;
    GNRect*                  _movingTuningRect;
    float                    _slideRuleAnchorOffset;
    bool                     _intervalMonitoring;
    GNCoord*                 _noteSelectionColumnWidth;
    GNCoord*                 _noteSelectionPlusScaleSelectionColumnWidth;
    bool                     _callUpdateElementsForNewPitchSystemInSetPitchSystem;
    bool                     _handlePreviewByHeartbeat;
    int32_t                  _clickedPitchIndexBeforeRunningOpenPanel;
    int32_t                  _methodsEditingPitchSystem;
    float                    _boxLabelFontHeight;
    bool                     _isScaleSelectionAvailable;
    int32_t                  _previousPitchIndex;
    bool                     _canExecuteDynamicJustTuning;
    bool                     _isScaleTuningEditable;
    bool                     _isScaleModeEditable;
    /*  */ void*             _window;
    /*  */ void*             _windowControllers;
    /*  */ void*             _toolbar;
};