// Reconstructed from MikeCore — 106 properties

struct MUElementAnalyzer {
    int64_t                  _engineSampleOffset;
    int32_t                  _engineIndex;
    float *                  _originalSignal;
    float *                  _originalSignalBufferWithMargin;
    int64_t                  _sampleCount;
    int64_t                  _nonSilentSampleCount;
    double                   _sampleRate;
    double                   _duration;
    double                   _parameterValuesPerSecond;
    int32_t                  _parameterDataSize;
    float                    _maxAmplitude;
    float                    _propertyPointsMagnitudeToEnvelopeAmplitudeFactorSum;
    float                    _propertyPointsMagnitudeToEnvelopeAmplitudeFactorWeightSum;
    bool                     _isPercussive;
    bool                     _isPolyphonic;
    float                    _pitchJumpsSum;
    float                    _pitchBarycenter;
    float                    _allPercussiveDecay;
    float                    _allRhythmicQuality;
    float                    _allTonality;
    float                    _allCentDiffPerMillisecond;
    float                    _allPitchRangePerNote;
    float                    _allEnergyRelevantRegionRatio;
    float                    _allAttackPeakQuality;
    float                    _allAttackPeakToEnergyRegionRatio;
    float                    _allMonophony;
    float                    _referenceAttackPeakValue;
    float                    _referencePeakRmsLevel;
    bool                     _origRMSValid;
    GNInt *                  _nonSilentRmsVals;
    int32_t                  _pitchMatrixTimePosCount;
    float *                  _pitchMatrix;
    bool                     _useDNA2ForPolyphonicDetection;
    int32_t                  _timeSliceCount;
    int32_t                  _foundPropertyPointCount;
    float *                  _polyPitchEnergyMatrixExtracted;
    float *                  _polyPitchEnergyMatrixOriginal;
    float *                  _polyPitchRelevanceMatrixExtracted;
    float *                  _polyPitchRelevanceMatrixOriginal;
    float *                  _polyPitchCentMatrixForAdditionalDisplay;
    int32_t                  _processedTimeSliceCount;
    int32_t                  _previousRenderedBackgroundDisplayType;
    float                    _previousTestValue1;
    float                    _previousTestValue2;
    float                    _previousTestValue3;
    float                    _previousTestValue4;
    int32_t                  _previousRelevanceRankLimit;
    int32_t                  _previousRelevanceRankLimitForNewPaths;
    float *                  _originalColumnEnergyOfPolyPitchEnergyMatrixInv;
    float *                  _posNoiseEnergies;
    float *                  _spectrogramMagnitudeSums;
    float *                  _filteredSpectrogramMagnitudeSums;
    int2FloatStruct *        _maxRelevancePropertyPointsOfCentMatrixColumns;
    bool                     _isMarkedAsPreliminaryItem;
    float                    _sortingValue;
    int32_t                  _harmonicNumber;
    int32_t                  _timePosIndexOfPitchCenterRelevanceStart;
    int32_t                  _timePosIndexOfPitchCenterRelevanceEnd;
    float                    _lowerSuggestedPitchRangeLimit;
    float                    _upperSuggestedPitchRangeLimit;
    float                    _itemDetectionQualityLimit;
    float                    _attackItemDetectionQualityLimit;
    float                    _attackItemDefaultDetectionQualityLimit;
    float                    _propertyPointsMagnitudeToEnvelopeAmplitudeFactor;
    float                    _itemDetectionVisualQualityLimit;
    float                    _attackItemDetectionVisualQualityLimit;
    int32_t                  _windowOverlapForTimeSlices;
    double                   _explicitTimeSliceTimeDistance;
    int32_t                  _modelSpectrumSize;
    int32_t                  _modelSpectraSemitoneCount;
    bool                     _decomposedAudioSignalsAreLoaded;
    bool                     _itemsAreNonAdjacentAtAttacks;
    bool                     _hasBestTempoDetection;
    bool                     _didRecalcAllElementsPeriodsAndPitchCentersFromDecomposedAudioSignals;
    bool                     _aTestFlag;
    bool                     _useOverallResidualItems;
    bool                     _updateDecomposedAudioSignalsImmediately;
    bool                     _isEditingDetection;
    int32_t                  _displayMatrixTimeSliceCount;
    int32_t                  _displayMatrixStartSliceIndex;
    int32_t                  _displayMatrixStartSliceIndexInRingBuffer;
    float *                  _energyRawMatrix;
    bool                     _decomposedAudioSignalsAreInvalid;
    bool                     _updateDecomposedAudioSignalsIsSuspended;
    bool                     _shouldHandleSibilants;
    bool                     _didPerformBreathSeparation;
    bool                     _findMonophonicPitchInFrequencyDomain;
    bool                     _isSingleInstrument;
    bool                     _isPitchToChordAdaptionEnabled;
    int32_t                  _separationChangeCount;
    float *                  _polyPitchCentMatrixForSum;
    float **                 _polyPitchCentMatricesForRawTracks;
    float **                 _spectrogramAmpEnvelopesForRawTracks;
    float **                 _filteredSpectrogramAmpEnvelopesForRawTracks;
    float *                  _ampNormalizingReference;
    float                    _averageAmpNormalizingReference;
    float *                  _polyPitchCentMatrixForDisplay;
    int32_t                  _previousRenderedBackgroundAudioSourceIndex;
    int32_t                  _previousOtherAudioSourceIndex;
    bool                     _stereoMixMode;
    bool                     _testFlag1;
    MUAudioSourceDescriptionType* _currentDescriptionType;
    double                   _sourceDuration;
    float                    _maxUsedPeriod;
    bool                     _elementsAreTonal;
    bool                     _isPreliminary;
};