// Reconstructed from MikeCore — 52 properties

struct MUFilterEngine {
    /*  */ void*             _sampleFramesToNextUpdate;
    /*  */ void*             _lastSampleFramesToNextUpdate;
    /*  */ void*             _isFirstComponentInQueue;
    /*  */ void*             _allowPeriodBasedPhaseReset;
    /*  */ void*             _isSibilant;
    /*  */ void*             _previousElementStartInPerformanceTime;
    /*  */ void*             _sourceComponentFadeOutSamplePositionInSource;
    /*  */ void*             _outputReadBufferOfChannel;
    /*  */ void*             _outputReadBufferSize;
    /*  */ void*             _processingBufferSize;
    /*  */ void*             _processedChannelCount;
    /*  */ void*             _sampleRateReductionForOutputReadBuffer;
    /*  */ void*             _sampleRateReductionForFourierProcessing;
    /*  */ void*             _sampleRateReductionsRatio;
    fcomplex **              _currentPhasesOfChannel;
    /*  */ void*             _currentPhaseIncrementsOfChannel;
    /*  */ void*             _currentSpectrumOfChannel;
    /*  */ void*             _accumulatedPhasesOfChannel;
    /*  */ void*             _previousPhasesOfChannel;
    /*  */ void*             _currentAmpsOfChannel;
    /*  */ void*             _previousAmpsOfChannel;
    char *                   _binPhaseProcessingCount;
    /*  */ void*             _fourierTransformer;
    /*  */ void*             _magnitudeValues;
    /*  */ void*             _spectrumMagnitudeFactors;
    /*  */ void*             _calcAuxBuffer0;
    /*  */ void*             _calcAuxBuffer1;
    fcomplex *               _prevPhaseIncrements;
    /*  */ void*             _processingBuffersOfChannel;
    /*  */ void*             _complexSpectrumOfChannel;
    /*  */ void*             _outputValues;
    /*  */ void*             _sourceReadBufferOfChannel;
    /*  */ void*             _fadeBufferOfChannel;
    /*  */ void*             _positionInOutputReadBuffer;
    /*  */ void*             _outputReadBufferValidRegionEndIndex;
    /*  */ void*             _currentBlockStepSizeInOutputReadBuffer;
    /*  */ void*             _constantProcessBlockSize;
    /*  */ void*             _outputReadBufferValidRegionEndIndexDouble;
    /*  */ void*             _sourceSampleIndexForOutputReadBufferStart;
    /*  */ void*             _currentSourcePeriod;
    /*  */ void*             _bufferStartTime;
    /*  */ void*             _bufferEndTime;
    /*  */ void*             _sourceSamplePositionIncrementForOriginalTempo;
    /*  */ void*             _invSourceSamplePositionIncrementForOriginalTempo;
    /*  */ void*             _useCubicInterpolation;
    /*  */ void*             _sumStereoToMono;
    /*  */ void*             _processStereoChannelsSeparately;
    /*  */ void*             _shouldUseMidAndSideSignal;
    /*  */ void*             _useMidAndSideSignal;
    /*  */ void*             _isFadingIn;
    /*  */ void*             _isFadingOut;
    /*  */ void*             _outputReadBufferIsFaded;
};